### ISSUE TITLE
Stacked Bar Graphs Not Stacked

### ISSUE THREAD

**Issue by jmcglory** [mariusmuntean/ChartJs.Blazor#111]
Describe the bug

I noticed in my graphs but then checked https://iloveblazor.com/StackedBarChart has the same behaviour. Bars are not stacked on top of each other but seem to be behind each other.

For example on the example column B consists of
Red = 3
Green = 5
Blue = 6

So with all of them on it should total 14 but it only goes up to 6

Chart Js does not behave the same, it stacks them on top of each other
https://www.chartjs.org/samples/latest/charts/bar/stacked.html

Which Blazor project type is your bug related to?
I am using server side but I imagine it affects both

Which charts does this bug apply to?
https://iloveblazor.com/StackedBarChart 

Expected behavior

On Chart Js the bars generally stay the same size but the axis change to suit.
https://www.chartjs.org/samples/latest/charts/bar/stacked.html

**Comment by Joelius300** [comment]
Thanks for the report!

You'll need to also make the y-axis stacked as well, otherwise this is the expected behaviour. I have not tested it but try this:

```
YAxes = new List<CartesianAxis>
{
    new BarLinearAxis
    {
        Stacked = true
    }
}
```

We should change our sample to reflect the one from chart.js otherwise it just causes confusion. The goal is to port every official chart.js sample to blazor anyway but we're not ready for that yet.

**Comment by Joelius300** [comment]
Closing this now as the samples have been completely redone for 2.0 and the stacked bar sample now behaves the same as the official Chart.js one. Unfortunately, the samples aren't hosted anywhere yet but if you run them yourself, you should see the expected behaviour.

Thanks for reporting.
