### ISSUE TITLE
Scatter Chart Axis Label?

### ISSUE THREAD

**Issue by JasonIrby** [mariusmuntean/ChartJs.Blazor#123]
Hi.  I was looking through the samples and can't figure out how to show a Label on the X and Y axis.
I got numbers showing but I want to label what units those number are representing.

Thanks.

**Comment by Joelius300** [comment]
Unfortunately, that wasn't possible to configure until #121. You'll be able to do so in release 2.0.

As a temporary workaround you can use this:

1. Create a new class which has the property for configuring the axis label.
```csharp
class FixedScatterAxis : ScatterAxis
{
    public ScaleLabel ScaleLabel { get; set; }

    public FixedScatterAxis()
    {
        Display = true;
    }
}
```
2. Use that class instead of `ScatterAxis`
```csharp
// for example
XAxes = new List<ScatterAxis>
{
    new FixedScatterAxis
    {
        ScaleLabel = new ScaleLabel
        {
            LabelString = "Custom axis",
            FontColor = ColorUtil.ColorString(255, 0, 0)
        }
    }
}
```

I'm glad I understood what you wanted to achieve but for faster support and simpler communication, please use the template we provided :)  
I don't know if you check the [official Chart.js docs](https://www.chartjs.org/docs/latest/) but there's a section called `Labelling` under `Axes` ([here](https://www.chartjs.org/docs/latest/axes/labelling.html)). Obviously you couldn't have applied the properties there to C# since they simply don't exist in the latest nuget release, but seeing that link helps us to faster get a workaround to you.

**Comment by JasonIrby** [comment]
Yep.  That worked.

Thanks.
