### ISSUE TITLE
Prerelease 2.0: Error TS18003 Build: No inputs were found in config file..

### ISSUE THREAD

**Issue by andean00** [mariusmuntean/ChartJs.Blazor#149]
Hi guys, great work ! I am using this library for the first time in Blazor wasm. Please note that I upgraded my entire project to .NET 5 RC1 and I am using VS Preview 2019.
After following the installation instructions, when I try to debug the project, I get this message: 
Error	TS18003	Build:No inputs were found in config file 'MYPATH/.nuget/packages/chartjs.blazor/2.0.0-preview1/contentFiles/any/netstandard2.1/tsbuild/release/tsconfig.json'. 
Specified 'include' paths were '["../../wwwroot/ts/*.ts"]' and 'exclude' paths were '[]'.

Can you please telle me what is wrong ? 
Thanks and regards !

J

**Comment by Rowingwolf** [comment]
Great question. Had the same issue.  Reverted back to most current release.  Haven't seen much progress since June so wondering if there is a plan to upgrade for .Net 5??  Could use some of the speed improvements .Net 5 offers.

**Comment by Joelius300** [comment]
Thank you for the report.

I know of this bug and I believe it makes the preview release more or less unusable (but haven't tested it). This is very unfortunate but @mariusmuntean made the changes to the TypeScript related stuff and I don't have the resources to look into it currently. I should also mention that while I still hope for Marius to come back and fix this, I have not heard from him on any of the issues where he was mentioned, nor on private channels I have with him.

That being said, we would greatly appreciate any insights on this and I'll gladly merge a PR which fixes this.

Tagging @BorisGaliev @alessandro-gargiulo and @fededim because all of you have reported this issue in one way or the other. Thank you and I hope we can find a fix :)



Ps. @andean00 please fill out the prepared issue template next time, it helps us a lot.

**Comment by gsutra** [comment]
I get this error when referencing the nuget ChartJs.Blazor.2.0.0-preview1.nupkg, but **not** when referencing source projet. Maybe the problem occurs during pack nuget ?

**Comment by Joelius300** [comment]
Hey everyone.  

I fixed this issue in the most recent commit but I don't belive the solution is perfect. I spent hours trying to find a working solution but no matter what I tried, the tsconfig file(s) always got packed in the nuget package which resulted in this error here.  
The solution for now is to completely remove the tsconfig files and directly work with the TypeScript msbuild target in the csproj. Again, I don't believe this is perfect but I have not found any other way that works.

Now what? Release 2.0 should soon be done, I only have a few things left I want to do before releasing it. Since I don't have access to the NuGet page and we settled on uploading prereleases manually (not via the releases branch), I cannot publish the second preview release (that's also why it's not taged). Until then, you'll have to reference the project directly or build the nuget yourself.

On a different note.. I don't know if anyone has noticed but I opened the [Joels Legacy](https://github.com/mariusmuntean/ChartJs.Blazor/projects/4) project which contains some thoughts and ideas I have (had) for the project. Many of them are old, some are small, some bigger but I just don't have the time to implement them. This ongoing trend of me losing time and motivation to continue work on this library, with the addition of the repo owners absence, has made me think that I should stop my involvement here. I don't want to disappear silently and my goal is to publish 2.0 before moving on to other projects but I made this GitHub project just in case :)

I really hope someone with enough time and motivation to keep this project going can take over. Don't hesitate to contact us if you think that's something you'd like to do.
