### ISSUE TITLE
LineChart with Multiple Axes

### ISSUE THREAD

**Issue by mariohik** [mariusmuntean/ChartJs.Blazor#151]
### Describe your question
How can I set the Type = AxisType.Category?

### Which Blazor project type is your question related to?
- Client-Side

### Which charts is this question related to?
Line

### Additional context
I'm trying to set the Type = AxisType.Category, but it's readonly.

_Property or indexer 'LinearCartesianAxis.Type' cannot be assigned to -- it is read only_

**Comment by mariohik** [comment]
For help you guys unterstand me, I'm trying to achieve this graph [Multiple Axes](https://www.chartjs.org/samples/latest/charts/line/multi-axis.html), with XAxes = Months

**Comment by Joelius300** [comment]
I'm sorry, I don't quite understand your question. In order to achieve the multiple axis sample, you don't need to explicitly set the axis type.

Just use a single `CategoryAxis` in the `XAxes` and two `LinearCartesianAxis` in the `YAxis`. Then you can assign an id to an axis and use that same id in your dataset.

Check the source for the sample you sent (via GitHub or the devtools) and you'll see the config used. It's pretty much the same in C#, just different syntax and casing.

**Comment by mariohik** [comment]
Thank you! Worked.
