### ISSUE TITLE
LinearCartesianTicks Callback

### ISSUE THREAD

**Issue by Shashmeer** [mariusmuntean/ChartJs.Blazor#173]
Hi,
I'm having trouble getting my tick callback method to fire in my server-side app
My testing so far has been on a stacked bar chart
Here is my code, the callback does not get called, and the format of the ticks of the chart stay as the default

```
private BarConfig _config;
protected override void OnInitialized()
{
    _config = new BarConfig
    {
        Options = new BarOptions
        {
            Scales = new BarScales
            {
                XAxes = new List<CartesianAxis>
		{
                    new BarCategoryAxis
                    {
                        Stacked = true,
                    },
                },
                YAxes = new List<CartesianAxis>
		{
                    new BarLinearCartesianAxis
                    {
                        Stacked = true,
                        Ticks = new LinearCartesianTicks()
                        {
                            FontSize = 16,
                            Callback = new DelegateHandler<AxisTickCallback>(YTickCallback)
                        }
                    }
                }
            }
        }
    };
}

private string YTickCallback(JValue value, int index, JArray values)
{
    return $"{value:C2}";
}
```

**Comment by Joelius300** [comment]
You're correct. Although this code is fine and will work on client-side Blazor (tested), [callbacks with return value not supported on server-side Blazor](https://github.com/mariusmuntean/ChartJs.Blazor/issues/90).

If you open the developer tools of your browser, you should see a console message like this:
![image](https://user-images.githubusercontent.com/52202086/103227770-75963180-492f-11eb-8c57-ad7d8d42e57d.png)

In order to achieve the result you want, you'll have to write a JavaScript method and attach it with a `JavaScriptHandler`. Check the XML-docs by hovering over the types and properties. If you need help with `JavaScriptHandler`, you can comment below and I'll try to give you instructions.

The underlying problem here is well known and documented under #90 so I'll close your issue. If you have any ideas on how to solve this issue, comment on #90. Thanks!

**Comment by Shashmeer** [comment]
Thank you for your prompt reply, and your work on this library!

**Comment by Joelius300** [comment]
Perfect, I'm glad you got it working. If you have any other questions just open a new issue :)
