### ISSUE TITLE
Support for time-axis

### ISSUE THREAD

**Issue by NeilMacMullen** [mariusmuntean/ChartJs.Blazor#27]
From the jschart documentation https://www.chartjs.org/docs/latest/axes/cartesian/time.html Chart.js can support time-series axes by passing in a Date for the x value.  Just wondering if this could be supported in this package?  AFAICS, it could be done in a number of ways - simplest would be to derive TimePoint from Point and treat the x coordinate as DateTime.ticks before converting to a JS Date on interop?

**Comment by SeppPenner** [comment]
If I was you, I would take a look at https://github.com/Joelius300/ChartJSBlazor. This project is maintained at least.

**Comment by Joelius300** [comment]
This was added to the library on Jun 23. I'm telling you the date because back then I was a git noob and I don't have a PR to show you. Anyway, it's implemented now and you can see it working live for a [line-chart](https://www.iheartblazor.com/TimeLineChart) and a [bar-chart](https://www.iheartblazor.com/TimeBarChart).
