### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by SeppPenner** [mariusmuntean/ChartJs.Blazor#34]
I just wanted to know whether this project is still maintained or not.

**Comment by Joelius300** [comment]
Good question. If you'd like a features to be implemented, take a look at [my clone of this](https://github.com/Joelius300/ChartJSBlazor) - maybe I have what you want. I didn't fork it because there were too many errors in the samples when updating to preview6 and I only really cared about the line chart. There were however a lot of errors e.g. options in the wrong place in the tree, things that got serialized the wrong way (special enums), etc.   
I updated the library to the newest preview (preview6) adapted some pull requests that seemed worth implementing. I also fixed many of the errors I was able to find, added a lot of documentation to make it more understandable without having to look up the chartJs docs. Furthermore I added some features I personally wanted/required and also some people seemed to want (there are mentions in issues) like TimeAxis for the Linechart and strongly typed Datasets for line- and barcharts.
I have also done a lot of research regarding the null-value serialization that gives chartJs some troubles. You can read more about that in [this issue](https://github.com/Joelius300/ChartJSBlazor/issues/2).

Take a look at it and let me know what you think of it and potential feature ideas.

Note: I do not take credit for most of my library. I have added an MIT-license to my project because in the .csproj-file of the original library it says that it's MIT-licensed. If there are any problems with that, please let me know.

**Comment by SeppPenner** [comment]
@Joelius300 I don't believe that it is still maintained. I have already seen your project, I will give it a try.

> Take a look at it and let me know what you think of it and potential feature ideas.
One first idea is to create a new nuget package of your project so that more people can find it / use it.

>Note: I do not take credit for most of my library. I have added an MIT-license to my project because in the .csproj-file of the original library it says that it's MIT-licensed. If there are any problems with that, please let me know.

I have seen the missing license in this project, I have created https://github.com/mariusmuntean/ChartJs.Blazor/pull/36 exactly for this case 😄

**Comment by SeppPenner** [comment]
@Joelius300 I've opened some issues in the project, just for reference.

**Comment by SeppPenner** [comment]
It's obviuosly not. We should all move to https://github.com/Joelius300/ChartJSBlazor and support @Joelius300 with the work there.
