### ISSUE TITLE
BarChart color not being applied

### ISSUE THREAD

**Issue by ghofman2** [mariusmuntean/ChartJs.Blazor#4]
Hello,
Very much enjoying what you've built here so far. I am experiencing an issue where the color of my bar chart bars are grey no matter what color I specify (I have tried using both hex and rgba). On your editable showcase, the color seems to apply fine. The BarChartData I am passing to my barchart looks as follows:

```
                Data = new BarChartData
                {
                    Labels = prevSixMonthNames,
                    Datasets = new List<BaseBarChartDataset>
                        {
                            new BarChartDataset
                            {
                                BackgroundColor = "#007bff",
                                Label = "Earnings",
                                Data =  new List<object>{9, 8, 7, 6, 5},
                                BorderWidth = 1,
                                BorderColor = "#0829FF",
                                HoverBackgroundColor = "#98F095",
                                HoverBorderColor = "#43F049",
                                BorderSkipped = null
                            },
                            new BarChartDataset
                            {
                                BackgroundColor = "#FF0F27",
                                Label = "Expenses",
                                Data = new List<object>{1, 2, 3, 4, 5},
                                BorderWidth = 1,
                                HoverBackgroundColor = "#98F095",
                                HoverBorderColor = "#43F049",
                                BorderColor = "#A30A19",
                                BorderSkipped = null,
                            }
                        }
                }


```

**Comment by ghofman2** [comment]
May be related to issue #3

**Comment by ghofman2** [comment]
After further research and troubleshooting, I've discovered if I hard code the model on the client side, the colors render correctly. If I pass that same hard coded model from the server side to client side, then the colors do not render correctly. I've verified that the `BackgroundColor` and all other fields are set correctly both in fiddler and by debugging the client side. The mdoel used between the two examples was the exact same.

**Comment by mariusmuntean** [comment]
Hi @ghofman2 ,

Sorry for taking so long to reply(dayjob and Christmas preparations :D).
I will find some time during this week to look into this.

Cheers!

**Comment by mariusmuntean** [comment]
@ghofman2 In the SimpleBarChart sample I replaced the Data property of the BarChartConfig with the Data that you posted and the colors looked fine (red and blue).

I couldn't really understand what exactly you mean when you say that you pass the model (presumably including color info) from the server to the client. I would need more context information there.

Is it possible to give me a high-level explanation of how exactly you render the charts? Also, a code sample that reproduces the issue would be great. Anonymize it if it isn't an open source project (you could fake a server response by introducing a delay in an async method).

Finally, I googled around a bit and the things that I would look into next would be:

- Did you make a mistake like this guy?: https://stackoverflow.com/questions/42939098/chart-js-donut-chart-remains-grey-no-color

- Do you maybe display an empty chart and then, after a backend response, update the same chart's data? In the samples, you can see that I override the `OnAfterRender()` method and call something like `barChart.Reload();`. That's because the charts would otherwise not be shown after navigating to another sample and then back. That is something I'm not happy with, but for now I don't have an elegant solution.

- Google around for something like "ChartJs grey background color". It is possible that your issue stems from something completely different.
