### ISSUE TITLE
Migration: Add support for datalabels plugin

### ISSUE THREAD

**Issue by SeppPenner** [mariusmuntean/ChartJs.Blazor#40]
Migrated from https://github.com/Joelius300/ChartJSBlazor/issues/34:

Maybe support https://github.com/chartjs/chartjs-plugin-datalabels.

I don't have an idea how at the moment, but it must be possible.

**Comment by Joelius300** [comment]
As mentioned [here](https://github.com/mariusmuntean/ChartJs.Blazor/issues/79#issuecomment-605513034) you can configure the plugins on a per chart basis from now on (not released on nuget but implemented since #91). This means that all the per chart plugin configurations can be now done directly. You still need to implement the plugin option class youself (or use an anonymous object) and you also need to handle the registration directly via JavaScript (or interop). Also to configure the plugin on dataset level, you will need to subclass the dataset you're using and adding the plugin option there too.

Now this doesn't mean the datalabels plugin is supported, just plugins in general. But now we can start discussing how to implement this plugin. I'm thinking we might want another namespace, something like `ChartJs.Blazor.Plugins` (these are subject to change in #78), where we put configuration classes for the plugins that can then be used in the plugin options without having to write these classes yourself. For plugins that are very popular and benefit from configuration, this seems like a feature worth implementing.

As already mentioned in the original issue (back in the other repo), plugins have low priority for now. It's best to invest the available time for fixing current issues but I thought I'd update this issue.

**Comment by Joelius300** [comment]
@larschristensen20 has provided [a nice sample](https://github.com/mariusmuntean/ChartJs.Blazor/issues#issuecomment-749501491) so I'll close this for now.

Thank you @larschristensen20!
