### ISSUE TITLE
Tooltip overflow is hidden

### ISSUE THREAD

**Issue by mRmEEeZ** [mariusmuntean/ChartJs.Blazor#75]
### Describe the bug
Tooltip overflow is hidden when tooltip height is longer than the canvas

### Which Blazor project type is your bug related to?
- Server-Side

### Which charts does this bug apply to?
BarCharts

### Expected behavior
not to be hidden

### Screenshots
![Untitled](https://user-images.githubusercontent.com/57133128/73588555-b4332a00-44db-11ea-9186-5c7c7c732bee.png)

**Comment by mRmEEeZ** [comment]
also how to hide data with null 'Nan' or 0 values from the tooltip ?

**Comment by Joelius300** [comment]
Thanks for the report!

Can you provide a jsfiddle where that overflow isn't hidden? Since the tooltip is drawn onto the canvas I'm not sure if this is a bug but I may be wrong. If this is indeed a bug I have no idea what would be causing it, do you?

> also how to hide data with null 'Nan' or 0 values from the tooltip ?

You can do that with the [tooltip filter-callback](https://www.chartjs.org/docs/latest/configuration/tooltip.html#filter-callback). Currently those are not supported but you can download and manually build the library from [Joelius300/ChartJs.Blazor/robust-js-interop](https://github.com/Joelius300/ChartJs.Blazor/tree/robust-js-interop) where that's supported. I have started this branch with support for more and scalable callbacks to javascript and C#. As you will see, on server-side blazor, callbacks with a return value (like that filter) are not supported; only on client-side.  
The PR (draft) for this feature is #70. Also read #62 about this.

**Comment by mRmEEeZ** [comment]
i think i will wait for the tooltip filter-callback
and for the hidden overflow of tooltip maybe because it is out of the canvas and not rendered on html

**Comment by Joelius300** [comment]
Yes I'm pretty sure it won't get rendered anyway if it's not on canvas so that wouldn't be something we can fix. Maybe I'm wrong, some chart.js pro come and correct me :)

The filter-callback stuff was a side-question to this issue and the other one is resolved from our side. Do you think you could close this issue or do you have a good reason to keep it open? :)
