### ISSUE TITLE
Sample app Menu after resizing 

### ISSUE THREAD

**Issue by win32nipuh** [mariusmuntean/ChartJs.Blazor#80]
I have run the server app, the site appears in Chrome, than I resized it and receive the result as in attachment

<img width="619" alt="ChartjsBlazor1" src="https://user-images.githubusercontent.com/5189614/76427130-3866b000-63ac-11ea-8bda-b46148701776.png">

**Comment by Joelius300** [comment]
Thanks for the report.

Currently there are a lot of things that need work. I would rather focus on those instead of polishing the samples. As far as I'm concerned the samples show the usage of the library even though they aren't perfect. I hope you understand that it's more important to me to drive the library forwards instead of using my very limited time for the samples.

**Comment by win32nipuh** [comment]
Ok, I understand, you are right. 
I have reported it only FYI ;-)

**Comment by Joelius300** [comment]
I'll reopen it just so it's still there. It has low prioritiy but you're right; if we (for some reason) have a lot of resources/time we should correct it :)
