### ISSUE TITLE
Special case for '21st' (not '21th') dataset in sample

### ISSUE THREAD

**Issue by metalmine** [mariusmuntean/ChartJs.Blazor#81]
### Describe the bug
There's no logic for 21st data set, it becomes 21th dataset.

### Which Blazor project type is your bug related to?
- Client-Side
- Server-Side

### Which charts does this bug apply to?
Any of them that can Add Datasets

### To Reproduce
Click Add dataset until you hit 21+

### Expected behavior
Show [21st Dataset]

### Screenshots
https://imgur.com/a/tVLCFiN

**Comment by Joelius300** [comment]
Thanks for the report.

Currently there are a lot of things that need work. I would rather focus on those instead of polishing the samples. As far as I'm concerned the samples show the usage of the library even though they aren't perfect. I hope you understand that it's more important to me to drive the library forwards instead of using my very limited time for the samples.

**Comment by metalmine** [comment]
Absolutely, I just wanted to document it.

**Comment by Joelius300** [comment]
I'm going to close this because from now on we'll use the same form as Chart.js which is "Dataset x". I think we should be able to avoid this situation this time around :)  Thanks for reporting.
