### ISSUE TITLE
When will the next version be released?

### ISSUE THREAD

**Issue by mikara89** [mariusmuntean/ChartJs.Blazor#85]
### Describe your question
I am using ChartJsLineChart and can't reverse y axes.
there is no option in LinearCartesianTicks class for setting that property.
I am using 1.0.3 version and can see that is fixed in code but not released.

### Which Blazor project type is your question related to?
- Server-Side

### Which charts is this question related to?

LineChart

**Comment by Joelius300** [comment]
Good question..

As I've written [before](https://github.com/mariusmuntean/ChartJs.Blazor/issues/71#issuecomment-601773391), I honestly don't know. @mariusmuntean is in charge of the nuget and he's the only collaborator that has the login to the ChartJs.Blazor nuget page. He also manages the demo-page.  He's not been active in this repo for quite some time now and has no contributions in the last few months.

That being said, I really don't want to push any blame on him. We're both doing this in our limited free time for, well, _free_ and there's lots of other things in our lifes. Also considering the circumstances this pandemic brings us, I don't know if he's more likely to come back or exactly the opposite. I've had to mention in many issues that I'm not able to update the nuget and I don't have much time currently.  
You can build the sources yourself and work with it directly. Considering how slow development is going in this repo, you aren't missing out on much.

I hope you understand that I'm really trying but I can't do more currently. I will pin this issue in hopes of reaching @mariusmuntean better and because it's a big question for this repo.

**Comment by Joelius300** [comment]
I talked to Marius about this and I should be able to release a new version myself now. 🎉

I will fix #86 and then release V 1.1 to nuget. If we do everything right and all the azure and nuget servers are working properly, you should soon get a new version. But please be patient, we'll get there :)

**Comment by mikara89** [comment]
ok, thanks very much.

**Comment by Joelius300** [comment]
[Release-1.1.0](https://github.com/mariusmuntean/ChartJs.Blazor/releases/tag/v1.1.0) is published and available [on nuget](https://www.nuget.org/packages/ChartJs.Blazor/) 🎉

I encourage you to read the release notes and try the new version. We will continue in the same fashion as long as time and circumstances allow us to. Thank you for your patience.
